# -*- coding: utf-8 -*-
"""
Created on Thu Jul 21 19:30:43 2022

@author: william_w
"""
import pickle as pk
vocab={"hola": "hello",
       "hablo": "i speak",
       "él habla": "he speaks",
       "ella habla": "she speaks",
       "hablas": "you speak",
       "hablar": "to speak",
       "semana": "week",
       "mañana": "tomorrow",
       "en la mañana": "in the morning",
       "hoy": "today",
       "segundo": "second",
       "hora": "hour",
       "cuántos años tienes": "how old are you",
       "el reloj": "the watch",
       "hacer": "to do",
       "ir": "to go",
       "quiero": "i want",
       "él quiere": "he wants",
       "ella quiere": "she wants",
       "quieres": "you want",
       "usted quiere": "you want",
       "ver": "to see",
       "bueno": "good",
       "bien": "well",
       "triste": "sad",
       "lo siento": "i'm sorry",
       "adios": "goodbye",
       "el hombre": "the man",
       "la mujer": "the woman",
       "el niño": "the boy",
       "la niña": "the girl",
       "fácil": "easy",
       "difícil": "difficult",
       "dónde": "where",
       "beber": "to drink",
       "bebo": "i drink",
       "bebes": "you drink",
       "él bebe": "he drinks",
       "soy muy alto": "i am very tall",
       "estoy aburrido": "i am bored",
       "él está enfermo": "he is ill",
       "tu": "your",
       "tener": "to have",
       "tengo": "i have",
       "tienes": "you have",
       "ella tiene": "she has",
       "tenemos": "we have",
       "abolir": "to abolish",
       "almorzar": "to have lunch",
       "A qué hora almuerzas": "what time do you have lunch",
       "andar": "to walk",
       "cerrar": "to close",
       "conocer": "to know",
       "conozco": "i know",
       "conoces": "you know",
       "dormir": "to sleep",
       
       }
pk.dump(vocab,open("spanish.txt","wb"))
print(vocab)